#' Title Select features through the selection  of singular value vectors
#'
#' @param SVD SVD compued from matrix generated by partial summation of a tensor
#' @param cond Condition to select singular value vectors
#' @param de  Initial values to be used for optimization of standard deviation  
#' @param p0  Threshold value for the significance
#' @param breaks Number of bins of hitogram of P-values
#' @param input_all The ID of selected singular value vectors. If it is null, 
#' interactive mode is activated.
#'
#' @return List of lists that inlcudes P-vales as well as if individual
#'  features selected.
#' @export
#'
#' @examples
#' set.seed(0)
#' matrix1 <- matrix(runif(2000),200)
#' matrix2 <- matrix(runif(4000),200)
#' SVD <- computeSVD(matrix1,matrix2)
#' index_all <- selectFeatureRect(SVD,
#' list(NULL,rep(seq_len(2),each=5),rep(seq_len(2),each=10)),de=rep(0.5,2),
#' input_all=1)
selectFeatureRect <- function(SVD,cond,de=rep(1e-4,2),p0=0.01,
                              breaks=100,input_all=NULL)
    {
    interact<-FALSE
    if(is.null(input_all))
        {
            interact<-TRUE
            j<-1
            while(j %in% seq_len(dim(SVD$SVD$u)[2]))
                {
                    par(mfrow=c(1,2))
                    boxplot(SVD$SVD$u[,j]~cond[[2]],main=j)
                    abline(0,0,col=2,lty=2)
                    boxplot(SVD$SVD$v[,j]~cond[[3]],main=j)
                    abline(0,0,col=2,lty=2)
                    par(mfrow=c(1,1))
                    input <- menu(c("NEXT","PREV","SELCT"))
                    if (input==2){if (j!=1){j<-j-1}}
                    else if (input==3){ break}
                    else { if (j<dim(SVD$SVD$u)[2])j<-j+1}
                 }
            input_all <- j
    } 
        th <- function(sd,breaks,p0){
        P2 <- pchisq((u/sd)^2,1,lower.tail=FALSE)
        hc<- hist(1-P2,breaks=breaks,plot=FALSE)
        return(sd(hc$count[seq_len(sum(hc$breaks
                                       <1-min(P2[p.adjust(P2,"BH")>p0])))]))
        }
        index_all <- rep(list(NA))
        for (i in seq_len(2))
        {
            u<- scale(SVD[[i+1]][,input_all])
            sd <- optim(de[i],function(x){th(x,breaks,p0)},
                        control=list(warn.1d.NelderMead=FALSE))$par
            sd1 <- seq(0.1*sd,2*sd,by=0.1*sd)
            th0 <- apply(matrix(sd1,ncol=1),1,function(x){th(x,breaks,p0)})
            P2 <- pchisq((u/sd)^2,1,lower.tail=FALSE)
            plot.new()
            par(mfrow=c(1,2))
            plot(sd1,th0,type="o")
            arrows(sd,max(th0),sd,min(th0),col=2)
            hist(1-P2,breaks=breaks)
            par(mfrow=c(1,1))
            if (interact)
            {
                readline("Press Enter to proceed:")
            }
            index <- p.adjust(P2,"BH")<p0
            index_all[[i]] <- list(index=index,p.value=P2)
        }
        return(index_all)
    }
    